/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.EncargDep;
import logica.EncargDepLogica;
import logica.EncargadoLogica;
import modelo.Administrador;
import modelo.EncargadoDependencia;
/**
 *
 * @author Alex
 */
public class reasignarEncargado extends javax.swing.JFrame {

    /**
     * Creates new form reasignarEncargado
     */
    public reasignarEncargado(Administrador a) {
        initComponents();
        admin=a;
        DefaultComboBoxModel model=new DefaultComboBoxModel(endeLog.obtenerDocumentos().toArray());
        comboDoc.setModel(model);
        model=new DefaultComboBoxModel(endeLog.obtenerDependencias(comboDoc.getItemAt(comboDoc.getSelectedIndex())).toArray());
        comboDep.setModel(model);
        this.setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Encargado de dependencia");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        reasignar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        depAct = new javax.swing.JTextField();
        comboDep = new javax.swing.JComboBox<>();
        comboDoc = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

        reasignar.setText("Rasignar encargado");
        reasignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reasignarActionPerformed(evt);
            }
        });
        getContentPane().add(reasignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Documento del encargado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dependencia actual");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nueva dependencia asignada");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        depAct.setEditable(false);
        getContentPane().add(depAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 88, -1));

        comboDep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        comboDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDocActionPerformed(evt);
            }
        });
        getContentPane().add(comboDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoAzul.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        vistaAdministrador obj=new vistaAdministrador(admin);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void reasignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reasignarActionPerformed
        // TODO add your handling code here:
        try{
            String dep = depAct.getText();
            String depn= comboDep.getItemAt(comboDep.getSelectedIndex());
            String doc = comboDoc.getItemAt(comboDoc.getSelectedIndex());
            EncargDep emc = endeLog.buscarEncargado(dep, doc);
            EncargadoDependencia endep = enLog.getEncargado2(doc);
            boolean error = endeLog.reasignarEncargado(emc, dep, depn, endep);
            
            if(!error){
                JOptionPane.showMessageDialog(null, "Se reasigno correctamente");
                vistaAdministrador obj=new vistaAdministrador(admin);
                obj.setVisible(true);
                dispose();
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            return;
        }
    }//GEN-LAST:event_reasignarActionPerformed

    private void comboDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDocActionPerformed
        // TODO add your handling code here:
        String eng = comboDoc.getItemAt(comboDoc.getSelectedIndex());
        depAct.setText(endeLog.obtenerDepAsig(eng));
        
        DefaultComboBoxModel model=new DefaultComboBoxModel(endeLog.obtenerDependencias(comboDoc.getItemAt(comboDoc.getSelectedIndex())).toArray());
        comboDep.setModel(model);
    }//GEN-LAST:event_comboDocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboDep;
    private javax.swing.JComboBox<String> comboDoc;
    private javax.swing.JTextField depAct;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton reasignar;
    // End of variables declaration//GEN-END:variables
    private EncargDepLogica endeLog=new EncargDepLogica();
    private EncargadoLogica enLog = new EncargadoLogica();
    private Administrador admin;
}
