/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import logica.AdministradorLogica;
import modelo.Administrador;
import modelo.Dependencia;
import logica.DependenciaLogica;

/**
 *
 * @author usuario
 */
public class vistaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form vistaAdministrador
     */
    public vistaAdministrador(Administrador admin) {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Administrador");
        this.adminRegistrado=admin;
        setCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrarDependencia = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        estaSistema = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrarDependencia.setText("Registrar dependencia");
        registrarDependencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarDependenciaActionPerformed(evt);
            }
        });
        getContentPane().add(registrarDependencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 250, -1));

        jButton2.setText("Registrar encargado de dependencia");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 250, -1));

        jButton3.setText("Reasignar encargado de dependencia");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 250, -1));

        jButton4.setText("Generar reporte por usuario");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 250, -1));

        jButton5.setText("Cerrar sesion");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jButton7.setText("Generar reporte por tipo de solicitud");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 250, -1));

        estaSistema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Paranoico" }));
        estaSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estaSistemaActionPerformed(evt);
            }
        });
        getContentPane().add(estaSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 150, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Estado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoAzul.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        registroEncargado obj=new registroEncargado(adminRegistrado);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        reasignarEncargado obj=new reasignarEncargado(adminRegistrado);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        VistaReporteSolicitud obj=new VistaReporteSolicitud();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Interfaz obj=new Interfaz();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void registrarDependenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarDependenciaActionPerformed
        // TODO add your handling code here:
        registroDependencia obj=new registroDependencia(adminRegistrado);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_registrarDependenciaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // generar reporte usuario
        VistaReporteUsuario obj=new VistaReporteUsuario();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void estaSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estaSistemaActionPerformed
        // TODO add your handling code here:
        if(estaSistema.getSelectedIndex()==0){
            adminRegistrado.setEstadoSistema(false);
        }
        else 
            adminRegistrado.setEstadoSistema(true);
        adminLog.setEstadoSistema(adminRegistrado);
    }//GEN-LAST:event_estaSistemaActionPerformed

    private void setCombo(){
        if(adminLog.estadoParanoico())
            estaSistema.setSelectedIndex(1);
        else
            estaSistema.setSelectedIndex(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> estaSistema;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton registrarDependencia;
    // End of variables declaration//GEN-END:variables
    private Administrador adminRegistrado;
    private AdministradorLogica adminLog = new AdministradorLogica();
    private Dependencia depenRegistro;
    private DependenciaLogica depLog = new DependenciaLogica();
}
